## Introduction

uisum is an open-source interactive web app for visualising hidden states of LSTM networks trained on genomical dataset such as bacteria. The goal of uisum is to screen hidden states for unkown but common structural properties. The model behind uisum is generated by [altum](https://github.com/hiddengenome/altum), a R library with interface to Keras. The goal of uisum is to provide a view to precalulated state response of a variety of bacterial strains and to provide tools for the detection of such hidden features.

## Installation

if you using RStudio you can run this application on a local computer. It requires the R packages `Biostrings`, `shiny`, `keras`, `h5`, `dygraphs`. The R library `hiddengenome/altum` needs to be installed as it provides the main function of hidden state extraction. 


## Running uisum

To run uisum please start it as a R shiny server and point your browser to  [localhost:6681](http://http://localhost:6681). You may need to change the port dependent on your shiny installation. 

```bash
runApp()
```

## Usage

Please enter a genomic sequence (nucleotides) in the input area or upload a .fasta file. Hidden states will be infered using `hiddengenome/altum` and visualised. You can select different cells on the left. 

![Web app](/scr/images/figure.png)

